### ISSUE TITLE
Units selection

### ISSUE THREAD

**Issue by draaxk** [methusalah/OpenRTS#24]
- be able to select all unit of the same type (unity) present in screen by double clic on one.
- be able to add and remove a single unit from a selected group, by holding control key
- combine those two features

**Comment by wuendsch** [comment]
hi,
it's possible to translate this in english? thx

**Comment by methusalah** [comment]
done !

**Comment by wuendsch** [comment]
thx.
Is there already a concept for grouping units?

**Comment by methusalah** [comment]
We already group units in two ways : draw a rectangle, or select a unity

In both ways, the selection is kept by the Commander (model package) and the player's orders are performed by the controllers (controller.battlefield package).

BattlefieldController catches mouse draging to draw a rectangle, then select units in the endSelection() method on mouse released and give them to the Commander (model package). It seems that both Controller and Commander have the same code of rectangle selection that may be a doublon.

BattlefieldGUIController draws buttons for any unit type present in the screen at each frame (unities in context). On clic, it ask the Commander to select all units in the screen of the corresponding unity.

Commander have methods (or may gain methods) to add and remove units and group of units to the actual selection.

**Comment by roroah** [comment]
Following how starcraft (i'm taking it as reference since the unit selection is well done on that part) work concerning units selection when double clic, having the selection select all unit in a defined range is more accurate than all unit on the player screen. (ofc it should work for units of the same type)

**Comment by methusalah** [comment]
This is my actual quick and dirty implementation : unity buttons get all units in a circle around the center of the screen. I find it imprecise and unpredictable, but it must be tested in a real gaming situation.

**Comment by roroah** [comment]
That isn't quite what i wanted to mean, what i was talking about was when using the double clic, it select all unit around the initial unit on a defined range instead of selecting all unit visible on the screen of the same type,
Another implementation could be a mix of the two as selecting all unit visible on the screen + unit off-screen on a defined range. (this might be more accurate and look more like sc2 style since the main issue when only selecting unit the visible on screen it force the user to have all the unit on his screen before doing the selection)
