### ISSUE TITLE
Guide for asset contributions (Models, Units, sounds, GUI, maps)

### ISSUE THREAD

**Issue by poVoq** [methusalah/OpenRTS#57]
Would be nice to have some more details in the wiki how to expand the game asset-wise, especially how to contribute models, configure unit xmls, make maps, improve the GUI, contribute sound effects and music etc.

**Comment by methusalah** [comment]
I've begun something : https://github.com/methusalah/OpenRTS/wiki/Assets-contribution-guide

WIP !

**Comment by methusalah** [comment]
And this one for dataset : https://github.com/methusalah/OpenRTS/wiki/Dataset-contribution-guide

WIP too !

**Comment by poVoq** [comment]
Ok, so how would I actually contribute soundfx for example? These two seem appropriate and are licensed under CC-by:
http://opengameart.org/content/scifi-rts-status-vocals
http://opengameart.org/content/female-soldier-voice

**Comment by methusalah** [comment]
The engine doesn't support sounds for now, but you can put useful assets
into assets/sounds directory. I will try to add sound actor soon.

**Comment by poVoq** [comment]
About the unit meshes:
Skeletal animations and bone based particle emitters are supported right, but no mesh deformation (morphing?) via the bone? How do movable turrets work? And how does one have to set-up the animations? Is it possible to turn particle-emiters on and off as part of the animation (e.g. steam release on a certain animation part, or landing exhaust?)

Are specularity and normal-maps supported? How many UV maps are allowed per mesh? (not really planning to go overboard with texturing, but it would be good to know).

**Comment by methusalah** [comment]
the morphing is not supported for now for a simple and good reason : Jmonkey doesn't support it for now :) Of course, in lot of cases, skeletal can do the trick but I admit it may be limiting.

For turrets, two bones are needed : one attached to the body part and the other to the turret itself. between the two parts, there must be hided vertices, because the rotation will lead to twisted polygons.

Animation is launche in a dedicated AnimationActor, with only a name, speed and looping mode. This actor may be attached to a Unit or a Weapon (in the future to an Effect). You can see an exemple in assets/data/army/human/tank/weapon_actors.xml

For now, there is nos way to launch an actor (particle, animation, sound) synchronised with an animation event. It could be implemented but is not simple (create a long time goal issue). In the mean while, a more simple mechanism would allow to trigger an actor with a delay, and synchronise it. But this will not be sufficient to through a smoke at each step of your giant robot. This would be a hard work.

As far as I know, normal, glow and specular maps are allowed for models (glow shader may require activation). For UV maps I can't tell.

**Comment by methusalah** [comment]
Sounds are now supported via SoundActors. Test the human tank and see assets/data/army/human/tank actors XML files for examples.

**Comment by poVoq** [comment]
Great... will take me a few days to actually contribute something as I will be one a businesstrip the next couple of days. I hope I can find the time later next week.

**Comment by methusalah** [comment]
I've created a topic on the forum for the specific question of the 3D assets. let's close here if we are finished and continue on the forum : 

http://hub.jmonkeyengine.org/t/knowledge-base-and-style-guide-for-3d-assets/32614/1
