### ISSUE TITLE
Contributors Inn : Present yourself !

### ISSUE THREAD

**Issue by methusalah** [methusalah/OpenRTS#69]
This special issue is for us all ! Here we can present ourselves to learn more about all the contributors and other OpenRTS enthusiastics.

Don't be shy !

**Comment by methusalah** [comment]
First ! 

My name is Benoît, I'm french, living in Toulouse (south of France) and I'm 34. I'm married with three little boys :)

I'm a self-educated programmer and I code in Java and Javascript langages.

I'm working in something totally different (sales manager) and I code for pleasure, every night, everytime I can ! 

Nice to meet you all

**Comment by BRGCodeCampus** [comment]
My turn ;)

My name is David, French (as Benoit) I live in Tours (Middle land, 37) and I'm 15.

I learn Java on Ope,Classroom and the I started learning LWJGL (and C++ OpenGL) on my own, I love  mathematics and I try to optimize / find and correct bugs in programs during my free time.

I know OpenRTS since only a week and it seems well made. There's still things I don't understand but during the summer holidays , I think I will work a lot on it (maybe networking / scripting stuff)

**Comment by wuendsch** [comment]
Hi,
I am Mario from germany. I live in Dortmund (Ruhrgebiet) and I am (let my compute ... ) 34 years now. Since some weeks, I am happy married. 
I am a softwaredeveloper/-architect and I manage large software projects in a team. So it's needed to have a overview about the hole project and the big picture in my mind. In my free time I play Starcraft2 and I love programming in a funny project like OpenRTS. This is the perfect merge between these 2 hobbies ;-)

I am not so strong in OpenGL, Drawing view or creating models and meshes. The guys who are creating these things get all my respect. So lets hope, we get some of the these guys on board. We will need it, to show the potential of OpenRTS.

**Comment by poVoq** [comment]
I am Julius, also from Germany (and I grew up in a small town not too far from Dortmund ;) ) and am 33 years old. I guess I am somewhat well known in the FOSS game-dev scene, but more as an opinionated blogger and community moderator on freegamedev.net.

I would describe my skills as mostly 3D modeller, but with some basic understanding of programming... also long time exclusive Linux user and back in the day big time Starcraft1 fan (never liked the sequel much).

FOSS gamedev is strictly a hobby for me and due to my day job with an large humanitarian organisation my free-time is somewhat limited, but I enjoy 3D modelling in the evenings from time to time. Since a few weeks I am living in the Philippines for those that might wonder about time differences.

**Comment by wuendsch** [comment]
@poVoq the world is small ;-)

**Comment by roroah** [comment]
Hi, 
I'm Emmanuel from France, I live near Montpellier (in the south, 2hour from @methusalah, the world is really small finally.) I'm 27, I've ended school for a year now and I'm looking for job while trying to make game.
I'm mainly a 3D artist and I've self-taught myself some programing skill to be able to use Jme, I'm using it for about 2 year now.
While not looking for job I work on my project [1], since it currently imply a lot of programing, I haven't a lot of room to create 3D assets, well i can but i don't like the idea to have stuff sitting on my computer and be useless... So I'm looking for project where I can share some of my skill, this by making 3D assets related to these project while keeping room to have them usable for my own project.

Nice to meet you all.

[1] https://github.com/MultiverseKing

**Comment by methusalah** [comment]
let's continue this here http://hub.jmonkeyengine.org/t/contributors-presentations/32703

Please paste your presentation !
