### ISSUE TITLE
Problem with Eclipse

### ISSUE THREAD

**Issue by BRGCodeCampus** [methusalah/OpenRTS#70]
Hi,
My PC crashed while I was working on GUIs and now Eclipse says "Erreur : impossible de trouver ou charger la classe principale app.MainRTS" when I try to launch it.

I tried to delete and re-download the full project, noway, can't find the problem.
Do you have any idea ?

**Comment by wuendsch** [comment]
hi,
is there a class named app/MainRTS.java ? use a new empty workspace!
is it working with "./gradlew.bat run"?

**Comment by methusalah** [comment]
I confirm, the code won't compile since it appears that gradle search for lib in its cache.

In my eclipse set, the dependecies are to users/[me]/.gradle/caches/modules-2...

It began to create errors from the moment Mario imported com.jme.network, which I've never used and that is not in my cache.

Also, simpleXML.jar was missing in lib dir, I added it.

Mario, could you please download the dependencies into the lib directory for everyone to have a complete set up after cloning? Including external lib for offline compilation.

Thanks !

**Comment by wuendsch** [comment]
the dependency simple-xml is no manage directly by gradle. There is a "compile 'org.simpleframework:simple-xml:2.7.1' " entry in the build.gradle. You must force eclipse to refresh these deps => right click on the project core => gradle => refresh all 
You can check, if its a eclipse problem, if you can "./gradlew run" or "./gradlew build" on the command line.

**Comment by wuendsch** [comment]
I have cloned it into a fresh directory an the Application is running with "./gradlew run"

**Comment by methusalah** [comment]
Ok I tried to refresh all into the gradle menu, and it worked. Thanks ! Don't know why it wasn't downloading the missing deps.

@BRGCodeCampus Maybe it will work for you too? please give us news. Did you try "./gradlew run"?

**Comment by methusalah** [comment]
@BRGCodeCampus any news ?

**Comment by BRGCodeCampus** [comment]
It works now Thank you for your help. I start working on GUIs (but school first so not that many time to spend on it).
